version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    container_name: pg-dump-test
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
      - ./dumps/:/dumps/
